[package]
name = "circuits"
version = "0.1.0"
edition = "2024"

[dependencies]
halo2_proofs = { version = "0.3", default-features = false, features = ["dev-graph", "batch", "multicore"] }
ff = "0.13"
rand = "0.8"
